---
# tasks file for marathon
- name: Set Marathon hostname
  copy:
    content: "{{marathon_local_address}}"
    dest: /etc/marathon/conf/hostname
    mode: 0644
  sudo: yes

- name: remove marathon override
  file: path=/etc/init/marathon.override state=absent

- name: ensure marathon is running (and enable it at boot)
  service: name=marathon state=started enabled=yes

- name: Set Marathon consul service definition
  sudo: yes
  template:
    src: marathon-consul.j2
    dest: "{{ consul_dir }}/marathon.json"
  notify:
    - Restart consul
